<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdk.proto

namespace Agones\Dev\Sdk;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * time duration, in seconds
 *
 * Generated from protobuf message <code>agones.dev.sdk.Duration</code>
 */
class Duration extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 seconds = 1;</code>
     */
    protected $seconds = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $seconds
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Sdk::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 seconds = 1;</code>
     * @return int|string
     */
    public function getSeconds()
    {
        return $this->seconds;
    }

    /**
     * Generated from protobuf field <code>int64 seconds = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSeconds($var)
    {
        GPBUtil::checkInt64($var);
        $this->seconds = $var;

        return $this;
    }

}

