<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdk.proto

namespace Agones\Dev\Sdk;

if (false) {
    /**
     * This class is deprecated. Use Agones\Dev\Sdk\GameServer\Spec\Health instead.
     * @deprecated
     */
    class GameServer_Spec_Health {}
}
class_exists(GameServer\Spec\Health::class);
@trigger_error('Agones\Dev\Sdk\GameServer_Spec_Health is deprecated and will be removed in the next major release. Use Agones\Dev\Sdk\GameServer\Spec\Health instead', E_USER_DEPRECATED);

