<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdk.proto

namespace Agones\Dev\Sdk;

if (false) {
    /**
     * This class is deprecated. Use Agones\Dev\Sdk\GameServer\Status instead.
     * @deprecated
     */
    class GameServer_Status {}
}
class_exists(GameServer\Status::class);
@trigger_error('Agones\Dev\Sdk\GameServer_Status is deprecated and will be removed in the next major release. Use Agones\Dev\Sdk\GameServer\Status instead', E_USER_DEPRECATED);

