<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdk.proto

namespace Agones\Dev\Sdk;

if (false) {
    /**
     * This class is deprecated. Use Agones\Dev\Sdk\GameServer\Status\Port instead.
     * @deprecated
     */
    class GameServer_Status_Port {}
}
class_exists(GameServer\Status\Port::class);
@trigger_error('Agones\Dev\Sdk\GameServer_Status_Port is deprecated and will be removed in the next major release. Use Agones\Dev\Sdk\GameServer\Status\Port instead', E_USER_DEPRECATED);

