<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdk.proto

namespace Agones\Dev\Sdk;

if (false) {
    /**
     * This class is deprecated. Use Agones\Dev\Sdk\GameServer\Spec instead.
     * @deprecated
     */
    class GameServer_Spec {}
}
class_exists(GameServer\Spec::class);
@trigger_error('Agones\Dev\Sdk\GameServer_Spec is deprecated and will be removed in the next major release. Use Agones\Dev\Sdk\GameServer\Spec instead', E_USER_DEPRECATED);

