<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdk.proto

namespace Agones\Dev\Sdk;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A GameServer Custom Resource Definition object
 * We will only export those resources that make the most
 * sense. Can always expand to more as needed.
 *
 * Generated from protobuf message <code>agones.dev.sdk.GameServer</code>
 */
class GameServer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.agones.dev.sdk.GameServer.ObjectMeta object_meta = 1;</code>
     */
    protected $object_meta = null;
    /**
     * Generated from protobuf field <code>.agones.dev.sdk.GameServer.Spec spec = 2;</code>
     */
    protected $spec = null;
    /**
     * Generated from protobuf field <code>.agones.dev.sdk.GameServer.Status status = 3;</code>
     */
    protected $status = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Agones\Dev\Sdk\GameServer\ObjectMeta $object_meta
     *     @type \Agones\Dev\Sdk\GameServer\Spec $spec
     *     @type \Agones\Dev\Sdk\GameServer\Status $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Sdk::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.agones.dev.sdk.GameServer.ObjectMeta object_meta = 1;</code>
     * @return \Agones\Dev\Sdk\GameServer\ObjectMeta
     */
    public function getObjectMeta()
    {
        return $this->object_meta;
    }

    /**
     * Generated from protobuf field <code>.agones.dev.sdk.GameServer.ObjectMeta object_meta = 1;</code>
     * @param \Agones\Dev\Sdk\GameServer\ObjectMeta $var
     * @return $this
     */
    public function setObjectMeta($var)
    {
        GPBUtil::checkMessage($var, \Agones\Dev\Sdk\GameServer_ObjectMeta::class);
        $this->object_meta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.agones.dev.sdk.GameServer.Spec spec = 2;</code>
     * @return \Agones\Dev\Sdk\GameServer\Spec
     */
    public function getSpec()
    {
        return $this->spec;
    }

    /**
     * Generated from protobuf field <code>.agones.dev.sdk.GameServer.Spec spec = 2;</code>
     * @param \Agones\Dev\Sdk\GameServer\Spec $var
     * @return $this
     */
    public function setSpec($var)
    {
        GPBUtil::checkMessage($var, \Agones\Dev\Sdk\GameServer_Spec::class);
        $this->spec = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.agones.dev.sdk.GameServer.Status status = 3;</code>
     * @return \Agones\Dev\Sdk\GameServer\Status
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.agones.dev.sdk.GameServer.Status status = 3;</code>
     * @param \Agones\Dev\Sdk\GameServer\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Agones\Dev\Sdk\GameServer_Status::class);
        $this->status = $var;

        return $this;
    }

}

