<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdk.proto

namespace Agones\Dev\Sdk;

if (false) {
    /**
     * This class is deprecated. Use Agones\Dev\Sdk\GameServer\ObjectMeta instead.
     * @deprecated
     */
    class GameServer_ObjectMeta {}
}
class_exists(GameServer\ObjectMeta::class);
@trigger_error('Agones\Dev\Sdk\GameServer_ObjectMeta is deprecated and will be removed in the next major release. Use Agones\Dev\Sdk\GameServer\ObjectMeta instead', E_USER_DEPRECATED);

