<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdk.proto

namespace Agones\Dev\Sdk\GameServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * representation of the K8s ObjectMeta resource
 *
 * Generated from protobuf message <code>agones.dev.sdk.GameServer.ObjectMeta</code>
 */
class ObjectMeta extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string namespace = 2;</code>
     */
    protected $namespace = '';
    /**
     * Generated from protobuf field <code>string uid = 3;</code>
     */
    protected $uid = '';
    /**
     * Generated from protobuf field <code>string resource_version = 4;</code>
     */
    protected $resource_version = '';
    /**
     * Generated from protobuf field <code>int64 generation = 5;</code>
     */
    protected $generation = 0;
    /**
     * timestamp is in Epoch format, unit: seconds
     *
     * Generated from protobuf field <code>int64 creation_timestamp = 6;</code>
     */
    protected $creation_timestamp = 0;
    /**
     * optional deletion timestamp in Epoch format, unit: seconds
     *
     * Generated from protobuf field <code>int64 deletion_timestamp = 7;</code>
     */
    protected $deletion_timestamp = 0;
    /**
     * Generated from protobuf field <code>map<string, string> annotations = 8;</code>
     */
    private $annotations;
    /**
     * Generated from protobuf field <code>map<string, string> labels = 9;</code>
     */
    private $labels;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $namespace
     *     @type string $uid
     *     @type string $resource_version
     *     @type int|string $generation
     *     @type int|string $creation_timestamp
     *           timestamp is in Epoch format, unit: seconds
     *     @type int|string $deletion_timestamp
     *           optional deletion timestamp in Epoch format, unit: seconds
     *     @type array|\Google\Protobuf\Internal\MapField $annotations
     *     @type array|\Google\Protobuf\Internal\MapField $labels
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Sdk::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string namespace = 2;</code>
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * Generated from protobuf field <code>string namespace = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace($var)
    {
        GPBUtil::checkString($var, True);
        $this->namespace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uid = 3;</code>
     * @return string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>string uid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string resource_version = 4;</code>
     * @return string
     */
    public function getResourceVersion()
    {
        return $this->resource_version;
    }

    /**
     * Generated from protobuf field <code>string resource_version = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setResourceVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->resource_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 generation = 5;</code>
     * @return int|string
     */
    public function getGeneration()
    {
        return $this->generation;
    }

    /**
     * Generated from protobuf field <code>int64 generation = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGeneration($var)
    {
        GPBUtil::checkInt64($var);
        $this->generation = $var;

        return $this;
    }

    /**
     * timestamp is in Epoch format, unit: seconds
     *
     * Generated from protobuf field <code>int64 creation_timestamp = 6;</code>
     * @return int|string
     */
    public function getCreationTimestamp()
    {
        return $this->creation_timestamp;
    }

    /**
     * timestamp is in Epoch format, unit: seconds
     *
     * Generated from protobuf field <code>int64 creation_timestamp = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreationTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->creation_timestamp = $var;

        return $this;
    }

    /**
     * optional deletion timestamp in Epoch format, unit: seconds
     *
     * Generated from protobuf field <code>int64 deletion_timestamp = 7;</code>
     * @return int|string
     */
    public function getDeletionTimestamp()
    {
        return $this->deletion_timestamp;
    }

    /**
     * optional deletion timestamp in Epoch format, unit: seconds
     *
     * Generated from protobuf field <code>int64 deletion_timestamp = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeletionTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->deletion_timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> annotations = 8;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAnnotations()
    {
        return $this->annotations;
    }

    /**
     * Generated from protobuf field <code>map<string, string> annotations = 8;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAnnotations($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->annotations = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> labels = 9;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getLabels()
    {
        return $this->labels;
    }

    /**
     * Generated from protobuf field <code>map<string, string> labels = 9;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setLabels($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->labels = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ObjectMeta::class, \Agones\Dev\Sdk\GameServer_ObjectMeta::class);

